version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=user_for_cellosign
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=cellosign
  web:
    build: .
    command: python /usr/src/test_for_cellosign/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/test_for_cellosign/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: