# Generated by Django 3.2.4 on 2021-06-08 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cost_of_click', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
