# Generated by Django 3.2.4 on 2021-06-08 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_counters', '0002_auto_20210608_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
