# Generated by Django 3.2.4 on 2021-06-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_counters', '0003_alter_statistics_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='clicks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cost_of_click',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
